grails-app/domain/com/mcu/Fight.groovy
package com.mcu

class Fight {

    static belongsTo = [battle:Battle, character:Character]

    static mapping = {
        version false
     }

    static constraints = {

    }
}

grails-app/controllers/com/mcu/FightController.groovy
package com.mcu

import grails.plugin.springsecurity.annotation.Secured
import grails.validation.ValidationException
import static org.springframework.http.HttpStatus.*
import com.mcu.*;

class FightController {

    FightService fightService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE", fight:"PUT", getFightInfo:"PUT"]

    @Secured (['ROLE_USER'])
    def index(Integer max) {

        def fights = Fight.executeQuery("select C.name, F.battle.id from Fight as F, Character as C ,Battle as B where C.id = F.character.id and B.id = F.battle.id and B.deadline > current_date order by F.id")

        respond  fights
    }

    @Secured (['ROLE_USER'])
    def myCurrentFights (){
        def userID = params.userID
        def fights = Fight.executeQuery("select C.name, F.battle.id from Fight as F, Character as C ,Battle as B, Usuario as U where C.id = F.character.id and B.id = F.battle.id and U.id = B.user.id and U.id ="+userID+" and B.deadline > current_date order by F.id")
        respond fights
    }

    @Secured (['ROLE_USER'])
    def myEndedFights (){
        def userID = params.userID
        def fights = Fight.executeQuery("select C.name, F.battle.id from Fight as F, Character as C ,Battle as B, Usuario as U where C.id = F.character.id and B.id = F.battle.id and U.id = B.user.id and U.id ="+userID+" and B.deadline <= current_date order by F.id")
        respond fights
    }

    @Secured (['ROLE_USER'])
    def getFightInfo(){
        def fightID = params.fightID
        def fights = Fight.executeQuery("select C.name, C.description, F.battle.id, C.id from Fight as F, Character as C where C.id = F.character and F.battle.id ="+fightID+" order by F.id")
        respond fights
    }

    def show(Long id) {
        respond fightService.get(id)
    }

    def create() {
        respond new Fight(params)
    }

    @Secured (['ROLE_USER'])
    def fight (){
        def char1ID = params.character1
        def char2ID = params.character2

        def char1 = Character.findById(char1ID)
        def char2 = Character.findById(char2ID)


        def battle = Battle.findById(params.battle)


        Fight newFight = new Fight(battle: battle.id, character: char1.id)
        Fight second = new Fight(battle: battle.id, character: char2.id)

        fightService.save(newFight)
        fightService.save(second)

        respond Fight.findAllByBattle(battle)
    }

    @Secured (['ROLE_USER'])
    def save(Fight fight) {
        if (fight == null) {
            notFound()
            return
        }

        try {
            fightService.save(fight)
        } catch (ValidationException e) {
            respond fight.errors, view:'create'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'fight.label', default: 'Fight'), fight.id])
                redirect fight
            }
            '*' { respond fight, [status: CREATED] }
        }
    }

    def edit(Long id) {
        respond fightService.get(id)
    }

    def update(Fight fight) {
        if (fight == null) {
            notFound()
            return
        }

        try {
            fightService.save(fight)
        } catch (ValidationException e) {
            respond fight.errors, view:'edit'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'fight.label', default: 'Fight'), fight.id])
                redirect fight
            }
            '*'{ respond fight, [status: OK] }
        }
    }

    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }

        fightService.delete(id)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'fight.label', default: 'Fight'), id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'fight.label', default: 'Fight'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/fight/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'fight.label', default: 'Fight')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#create-fight" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="create-fight" class="content scaffold-create" role="main">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.fight}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.fight}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.fight}" method="POST">
                <fieldset class="form">
                    <f:all bean="fight"/>
                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/fight/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'fight.label', default: 'Fight')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#edit-fight" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="edit-fight" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.fight}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.fight}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.fight}" method="PUT">
                <g:hiddenField name="version" value="${this.fight?.version}" />
                <fieldset class="form">
                    <f:all bean="fight"/>
                </fieldset>
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/fight/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'fight.label', default: 'Fight')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#list-fight" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="list-fight" class="content scaffold-list" role="main">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:table collection="${fightList}" />

            <div class="pagination">
                <g:paginate total="${fightCount ?: 0}" />
            </div>
        </div>
    </body>
</html>

grails-app/views/fight/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'fight.label', default: 'Fight')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#show-fight" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="show-fight" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:display bean="fight" />
            <g:form resource="${this.fight}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.fight}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>