grails-app/domain/com/mcu/Usuario.groovy
package com.mcu

import groovy.transform.EqualsAndHashCode
import groovy.transform.ToString
import grails.compiler.GrailsCompileStatic
import grails.rest.*
import org.springframework.security.access.annotation.Secured

@GrailsCompileStatic
@EqualsAndHashCode(includes='username')
@ToString(includes='username', includeNames=true, includePackage=false)
class Usuario implements Serializable {

    private static final long serialVersionUID = 1

    String username
    String password
    boolean enabled = true
    boolean accountExpired
    boolean accountLocked
    boolean passwordExpired

    static hasMany = [battles:Battle, votes:Vote, favorites:Favorite]


    Set<Role> getAuthorities() {
        (UsuarioRole.findAllByUsuario(this) as List<UsuarioRole>)*.role as Set<Role>
    }

    static constraints = {
        password nullable: false, blank: false, password: true
        username nullable: false, blank: false, unique: true
    }

    static mapping = {
	    password column: '`password`'
        version false
    }
}

grails-app/controllers/com/mcu/UsuarioController.groovy
package com.mcu


import grails.validation.ValidationException
import groovy.json.JsonSlurper
import org.apache.commons.lang.RandomStringUtils
import org.springframework.security.access.annotation.Secured

import static org.springframework.http.HttpStatus.*
import grails.rest.RestfulController

class UsuarioController {

    UsuarioService usuarioService
    UsuarioRoleService usuarioRoleService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    @Secured (['ROLE_ADMIN'])
    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond usuarioService.list(params), model:[usuarioCount: usuarioService.count()]
    }

    @Secured(['ROLE_API'])
    def findID (){
        respond Usuario.findByUsername(params.username)
    }

    @Secured(['ROLE_API'])
    def changePassword(){
        def object = null
        try {
            def changePass = Usuario.findByUsername(params.username)

            int randomStringLength = 32
            String charset = (('a'..'z') + ('A'..'Z') + ('0'..'9')).join()
            String randomString = RandomStringUtils.random(randomStringLength, charset.toCharArray())
            changePass.setPassword(randomString)

            usuarioService.save(changePass)
            def jsonSlurper = new JsonSlurper()
            object = jsonSlurper.parseText('{ "newPass": "'+randomString+'" }')

        }catch(Exception e){
            println("No user found")
        }
        respond object
    }

    def show(Long id) {
        respond usuarioService.get(id)
    }

    def create() {
        respond new Usuario(params)
    }

    @Secured (['IS_AUTHENTICATED_ANONYMOUSLY','ROLE_API'])
    def save(Usuario usuario) {
        if (usuario == null) {
            notFound()
            return
        }

        try {
            usuarioService.save(usuario)
            Role role = Role.findByAuthorityLike('ROLE_USER')
            usuarioRoleService.save(UsuarioRole.create(usuario,role))

        } catch (ValidationException e) {
            respond usuario.errors, view:'create'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'usuario.label', default: 'Usuario'), usuario.username])+" exitosamente, ingrese sus datos para continuar"
                redirect (uri:'/')
            }
            '*' { respond "Usuario creado exitosamente", [status: CREATED] }
        }
    }

    def edit(Long id) {
        respond usuarioService.get(id)
    }


    @Secured(['ROLE_API','IS_AUTHENTICATED_ANONYMOUSLY'])
    def update(Usuario usuario) {
        if (usuario == null) {
            notFound()
            return
        }

        try {
            usuarioService.save(usuario)
        } catch (ValidationException e) {
            respond usuario.errors, view:'edit'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'usuario.label', default: 'Usuario'), usuario.id])
            }
            respond usuario
        }
    }

    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }

        usuarioService.delete(id)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'usuario.label', default: 'Usuario'), id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'usuario.label', default: 'Usuario'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }

}

grails-app/views/usuario/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'usuario.label', default: 'Usuario')}" />
    </head>
    <body>
        <a href="#create-usuario" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div id="create-usuario" class="content scaffold-create" role="main">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="ROLE_USER">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.usuario}">
            <ul class="errors" role="ROLE_USER">
                <g:eachError bean="${this.usuario}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>

            <g:form resource="${this.usuario}" method="POST" action="save">
                <fieldset>
                    <p class="info">
                        Complete the form below to create an account!
                    </p>
                    <g:hasErrors bean="${usuario}">
                        <div class="errors">
                            <g:renderErrors bean="${usuario}"/>
                        </div>
                    </g:hasErrors>
                    <p>
                        <label for="username">Username</label>
                        <g:textField name="username" value="${usuario?.username}"
                                     class="${hasErrors(bean:usuario,field:'username','errors')}"/>
                    </p>
                    <p>
                        <label for="password">Password</label>
                        <g:passwordField name="password"
                                         class="${hasErrors(bean:usuario,field:'password','errors')}" />
                    </p>
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/usuario/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'usuario.label', default: 'Usuario')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#edit-usuario" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="edit-usuario" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.usuario}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.usuario}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.usuario}" method="PUT">
                <g:hiddenField name="version" value="${this.usuario?.version}" />
                <fieldset class="form">
                    <f:all bean="usuario"/>
                </fieldset>
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/usuario/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'usuario.label', default: 'Usuario')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
    <div class="demo-charts mdl-color--white mdl-shadow--2dp mdl-cell mdl-cell--12-col mdl-grid">
        <h4 style="margin: 0 auto; padding-top: 12px" class="mdl-card__title-text">Current Users in database</h4>

        <f:table collection="${usuarioList}" properties="['username','battles','accountLocked']"/>

        <div class="pagination">
            <g:paginate total="${usuarioCount ?: 0}" />
        </div>
    </div>


    <div class="demo-separator mdl-cell--1-col"></div>

    <div class="demo-updates mdl-card mdl-shadow--2dp mdl-cell mdl-cell--4-col mdl-cell--4-col-tablet mdl-cell--12-col-desktop blueCard">

        <h4 style="margin: 0 auto; padding-top: 12px" class="mdl-card__title-text blueCardTitle">Add a User!</h4>
        <div style="background-color: white; height: 4px; width: 80%; margin: 0 auto; margin-top: 8px"></div>

        <g:form url="[action:'save',controller:'Usuario']" style="padding-top: 15px;padding-left: 10%">
            <fieldset>
                <table cellpadding="4" class="blueTable">
                    <tr>
                        <td style="text-align: right;"><label class="labelBlueForm">Username </label></td>
                        <td><g:textField name="usuario.username" class="blueTextField" required=""/><br/></td>
                    </tr>
                    <tr>
                        <td style="text-align: right;"><label class="labelBlueForm">Password </label></td>
                        <td><g:passwordField name="usuario.password" class="blueTextField" required=""/><br/></td>
                    </tr>
                    <tr>
                        <td colspan="2" align="center"><g:submitButton name="create" class="save blueButton" value="Create" /></td>
                    </tr>
                </table>
            </fieldset>
        </g:form>

    </div>

    </body>
</html>

grails-app/views/usuario/register.gsp
<!DOCTYPE html>
<html lang="en">
<head>
    <title><g:message code='springSecurity.login.title'/></title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <g:external dir="css" file="util.css" />
    <g:external dir="css" file="main.css" />

</head>
<body>
<div class="limiter">
    <div class="container-login100">
        <div class="wrap-login100">
            <div id="login" class="login100-form">
                <div class="inner">
                    <span class="login100-form-title p-b-26">
                        Sign up into MCU!
                    </span>

                    <br>

                    <g:if test='${flash.message}'>
                        <div class="login_message">${flash.message}</div>
                    </g:if>


                    <g:form resource="${this.usuario}" method="POST" action="save" class="login100-form" autocomplete="off">

                        <g:hasErrors bean="${usuario}">
                            <div class="errors">
                                <g:renderErrors bean="${usuario}"/>
                            </div>
                        </g:hasErrors>

                        <div class="wrap-input100">
                            <label for="username"><g:message code='springSecurity.login.username.label'/>:</label>
                            <g:textField id="username" name="username" value="${usuario?.username}"
                                         class="${hasErrors(bean:usuario,field:'username','errors')} input100"/>
                        </div>

                        <div class="wrap-input100">
                            <label for="password"><g:message code='springSecurity.login.password.label'/>:</label>
                            <g:passwordField id="password" name="password"
                                             class="${hasErrors(bean:usuario,field:'password','errors')} input100" />
                        </div>


                        <div class="container-login100-form-btn">
                            <p class = "wrap-login100-form-btn">
                                <p class = "login100-form-bgbtn"></p>
                        <g:submitButton style="background: #5bc0de" class="login100-form-btn" name="create" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                            </p>
                        </div>

                        <br>
                        <br>

                    </g:form>
                </div>
            </div>
        </div>
        <script>
            (function() {
                document.forms['loginForm'].elements['${usernameParameter ?: 'username'}'].focus();
            })();
        </script>

        <!--===============================================================================================-->
        <asset:javascript src="jquery-2.2.0.min.js"/>

        <asset:javascript src="bootstrap.min.js"/>

        <asset:javascript src="main.js"/>

</body>
</html>

grails-app/views/usuario/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'usuario.label', default: 'Usuario')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#show-usuario" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="show-usuario" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:display bean="usuario" />
            <g:form resource="${this.usuario}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.usuario}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>