grails-app/domain/com/mcu/Hero.groovy
package com.mcu

import org.springframework.security.access.annotation.Secured

class Hero extends Character{




    static constraints = {
    }
}

grails-app/controllers/com/mcu/HeroController.groovy
package com.mcu

import grails.validation.ValidationException
import org.springframework.security.access.annotation.Secured

import static org.springframework.http.HttpStatus.*

class HeroController {

    HeroService heroService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]


    @Secured(['ROLE_ADMIN','ROLE_USER'])
    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Character.findAllByType(TypeCharacter.findByName('Hero')),  model:[heroCount: heroService.count()]
    }

    @Secured('ROLE_ADMIN')
    def show(Long id) {
        respond heroService.get(id)
    }
    @Secured('ROLE_ADMIN')
    def create() {
        respond new Hero(params)
    }

    @Secured('ROLE_ADMIN')
    def save(Hero hero) {
        hero.setType(TypeCharacter.findByName('Hero'))
        println('Into save hero')
        if (hero == null) {
            notFound()
            return
        }

        try {
            heroService.save(hero)
        } catch (ValidationException e) {
            respond hero.errors, view:'create'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'hero.label', default: 'Hero'), hero.id])
                redirect (uri:'/hero/')
            }
        }
    }

    def edit(Long id) {
        respond heroService.get(id)
    }

    def update(Hero hero) {
        if (hero == null) {
            notFound()
            return
        }

        try {
            heroService.save(hero)
        } catch (ValidationException e) {
            respond hero.errors, view:'edit'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'hero.label', default: 'Hero'), hero.id])
                redirect hero
            }
            '*'{ respond hero, [status: OK] }
        }
    }

    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }

        heroService.delete(id)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'hero.label', default: 'Hero'), id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'hero.label', default: 'Hero'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/hero/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'hero.label', default: 'Hero')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#create-hero" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="create-hero" class="content scaffold-create" role="main">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.hero}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.hero}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.hero}" method="POST">
                <fieldset class="form">
                    <f:all bean="hero"/>
                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/hero/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'hero.label', default: 'Hero')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#edit-hero" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="edit-hero" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.hero}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.hero}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.hero}" method="PUT">
                <g:hiddenField name="version" value="${this.hero?.version}" />
                <fieldset class="form">
                    <f:all bean="hero"/>
                </fieldset>
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/hero/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'hero.label', default: 'Hero')}" />
        <g:external dir="css" file="styles.css" />
        <g:external dir="css" file="styles.css" />
    </head>
    <body>
    <div class="demo-charts mdl-color--white mdl-shadow--2dp mdl-cell mdl-cell--12-col mdl-grid">
        <h4 style="margin: 0 auto; padding-top: 12px" class="mdl-card__title-text">Current Heroes in database</h4>
        <f:table collection="${heroList}" properties="['photo_path','name','description','fights']"/>
    </div>

    <div class="demo-separator mdl-cell--1-col"></div>

    <div class="demo-updates mdl-card mdl-shadow--2dp mdl-cell mdl-cell--4-col mdl-cell--12-col-tablet mdl-cell--12-col-desktop blueCard">

        <h4 class="mdl-card__title-text blueCardTitle">Add a Hero!</h4>

        <div style="background-color: white; height: 4px; width: 80%; margin: 0 auto; margin-top: 8px"></div>

        <g:form url="[action:'save',controller:'Hero']" style="padding-top: 15px;padding-left: 10%">
            <fieldset>
                <table cellpadding="4" class="blueTable">
                    <tr>
                        <td style="text-align: right;"><label class="labelBlueForm">Hero Name </label></td>
                        <td><g:textField class="blueTextField" name="hero.name" required=""/><br/></td>
                    </tr>
                    <tr>
                        <td style="text-align: right;"><label class="labelBlueForm">Description </label></td>
                        <td><g:textField class="blueTextField" name="hero.description" required=""/><br/></td>
                    </tr>
                    <tr>
                        <td style="text-align: right;"><label class="labelBlueForm">Photo </label></td>
                        <td><g:textField style="border-radius: 6px" name="hero.photo_path" required=""/><br/></td>
                        <g:select name="hero.type" from="${com.mcu.TypeCharacter.findByName('Hero')}"
                                  optionKey="id"
                                  disabled="true"
                                  hidden="true"/>
                    </tr>
                    <tr>
                        <td colspan="2" align="center"><g:submitButton name="create" class="save blueButton" value="Create" /></td>
                    </tr>
                </table>
            </fieldset>
        </g:form>

    </div>
    <exa:datatable id="table1" items="${heroList}" />
    </body>

<script type="text/javascript" charset="utf-8">
    $(document).ready(function() {
        var datatable = Exa.Datatable.getDatatable('table2');
        $('#table1 tbody').on('click', '.btn-alert', function () {
            var data = datatable.getInstance().row($(this).parents('tr')).data();
            alert("Gender: " + data['sex']);
        });
    });
</script>

</html>

grails-app/views/hero/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'hero.label', default: 'Hero')}" />
    </head>
    <body>
        <a href="#show-hero" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="show-hero" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:display bean="hero" />
            <g:form resource="${this.hero}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.hero}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>